// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBfUuXGdyx3Dp95X-AVjXQlSYhAG7GP8',
    appId: '1:1003064338008:web:312c9b2775e4f7a033cc2d',
    messagingSenderId: '1003064338008',
    projectId: 'greenoffice360-2026',
    authDomain: 'greenoffice360-2026.firebaseapp.com',
    storageBucket: 'greenoffice360-2026.firebasestorage.app',
    measurementId: 'G-CKVLN8GDPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDczxPAOoxOLqGCDORZTsG8QzfEfKJrQNQ',
    appId: '1:1003064338008:android:1d518826b1daf2cf33cc2d',
    messagingSenderId: '1003064338008',
    projectId: 'greenoffice360-2026',
    storageBucket: 'greenoffice360-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpB3y22BpxvZPxebgXMqW_SZMpEh9rYk',
    appId: '1:1003064338008:ios:ac87587a2a945a4533cc2d',
    messagingSenderId: '1003064338008',
    projectId: 'greenoffice360-2026',
    storageBucket: 'greenoffice360-2026.firebasestorage.app',
    iosBundleId: 'com.example.greenoffice360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEpB3y22BpxvZPxebgXMqW_SZMpEh9rYk',
    appId: '1:1003064338008:ios:ac87587a2a945a4533cc2d',
    messagingSenderId: '1003064338008',
    projectId: 'greenoffice360-2026',
    storageBucket: 'greenoffice360-2026.firebasestorage.app',
    iosBundleId: 'com.example.greenoffice360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqBfUuXGdyx3Dp95X-AVjXQlSYhAG7GP8',
    appId: '1:1003064338008:web:1a48a04e5ac635b333cc2d',
    messagingSenderId: '1003064338008',
    projectId: 'greenoffice360-2026',
    authDomain: 'greenoffice360-2026.firebaseapp.com',
    storageBucket: 'greenoffice360-2026.firebasestorage.app',
    measurementId: 'G-FJK5N66XXE',
  );
}
